### ISSUE TITLE
Building StringVal: Constructor not found

### ISSUE THREAD

**Issue by snooze92** [laserson/impala-udf-devel#2]
Hi there!

Thanks for this work, it really helped me get started with compiling on Mac OS X.
I have one problem when trying to write this code:

```
StringVal buildResult(FunctionContext* context, std::string resultStr) {
    StringVal result(context, resultStr.size());
    memcpy(result.ptr, resultStr.c_str(), resultStr.size());
    return result;
}
```

The building of the .ll file works like a charm, and the UDF I wrote does work, but it's the compiling of the shared library that is failing. Since IR UDAs are not supported yet, I do need to fall back to shared libraries for User Defined Aggregates. This is the error I get:

```
Undefined symbols for architecture x86_64:
  "impala_udf::StringVal::StringVal(impala_udf::FunctionContext*, int)", referenced from:
      StringConcatUpdate(impala_udf::FunctionContext*, impala_udf::StringVal const&, impala_udf::StringVal const&, impala_udf::StringVal*) in uda-sample.cc.o
ld: symbol(s) not found for architecture x86_64
```

The constructor is in udf/udf.cc so I don't know exactly what I am missing to get the linker to work.

Also: where did you get that udf.cc file from? I would like to get a newer version!

**Comment by laserson** [comment]
Hey, glad this is helpful.  Indeed, you have also discovered that compiling UDAs to LLVM IR is simply not implemented at the moment.  Unfortunately, I would guess that successfully compiling UDAs on OS X is probably more trouble than it's worth at the moment.

But if you'd like to play around with it all, you can find all the code (including `udf.cc`) in the main Impala repo: https://github.com/cloudera/Impala
