### ISSUE TITLE
Brew does not seem to work

### ISSUE THREAD

**Issue by jarutis** [laserson/impala-udf-devel#3]
Hi,

Proposed `brew install impala-udf-devel` does not seem to work. Do I need to add some kind of repository. Would nice to mention it in the readme if it is a needed step.

```
$ brew install impala-udf-devel
Error: No available formula for impala-udf-devel
Searching taps...
```

**Comment by summerela** [comment]
I found the same issue. This is listed to be working on multiple websites, however, when searching through brew search, or through package descriptions, there are no brew packages for impala.

**Comment by wantflying** [comment]
i meet the same issue,can anyone have solved it?  brew install impala-udf-devel ,it cant work

**Comment by laserson** [comment]
This repository is not being maintained (and not clear if it ever even worked).
